name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        run: npm install -g pnpm

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2 
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test
